# Generated by Django 5.0.6 on 2025-01-13 10:59

import django.db.models.deletion
import movies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happening_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=500)),
                ('seats_he_booked', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('runtime', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('poster', models.CharField(max_length=200)),
                ('cover', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hallName', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.dates')),
            ],
        ),
        migrations.AddField(
            model_name='dates',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('seats', models.JSONField(default=movies.models.foo)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time', to='movies.location')),
            ],
        ),
    ]
